# Generated by Django 4.0 on 2024-11-05 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_user_if_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='if_staff',
            new_name='is_staff',
        ),
    ]
