# Generated by Django 4.0 on 2024-04-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_posts_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deteled',
            field=models.BooleanField(default=False),
        ),
    ]
