# Generated by Django 4.0 on 2024-04-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_deteled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_deteled',
            new_name='is_deleted',
        ),
    ]
