name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Ajusta la versión según sea necesario

      - name: Change directory
        run: cd social-media-app

      - name: Install dependencies
        working-directory:./social-media-app
        run: npm install

      - name: Build
        working-directory:./social-media-app
        run: npm ci && npm run build
