name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Ajusta la versión según sea necesario

      - name: Install dependencies
        run: cd social-media-app && npm install

      - name: Build
        run: cd social-media-app && npm ci && npm run build
